// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xospglrpmoqubokupgvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvc3BnbHJwbW9xdWJva3VwZ3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjgyMDAsImV4cCI6MjA2NjQwNDIwMH0.Z9YShKj_qLGycHxQoHlaPOu3ahPQUiW0qUB-fr0Wy2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'supabase.auth.token',
    flowType: 'pkce',
    // Add session validation options
    debug: false,
    // Refresh session 60 seconds before expiry
  }
});